---
title: "DQF Datasets"
output: html_document
date: "2023-06-12"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("00. datasets.R")
```

```{r}
one.outlier <- data.one.outlier(n.data=50,n.outliers=3, dist.outliers=6)
plot(one.outlier$data, col=one.outlier$labels,asp=1)
```

```{r}
halfmoon <- data.halfmoon()
plot(halfmoon$data, col=halfmoon$labels,asp=1)
```

```{r}
three.circles <- data.three.circles()
plot(three.circles$data,col=three.circles$labels,asp=1)
```

```{r}
library("scatterplot3d")
```

```{r}
double.helix <- data.double.helix()
data <- double.helix$data
labels <- double.helix$labels
scatterplot3d(data,color=labels)
```

```{r}
set.seed(47)

x <- seq(-2,5,.05)
n <- length(x)
x <- scale(x) + rnorm(n,0,.08)
y <- sin(x) + cos(2*x) + sin(2*x) + rnorm(n,0,.08)
data <- cbind(x,y)
labels <- rep(2,n)

x <- runif(100,-2,2)
y <- runif(100,-2.5,2)
n.labels <- rep(1,length(x))
noise <- cbind(x,y) 

data <- rbind(data,noise)
data <- scale(data)
nrow(data)
plot(data,col=c(labels,n.labels),asp=1)

distance_mat <- dist(data, method = "euclidean")
Hierar_cl <- hclust(distance_mat, method = "single") # p1
clusters <- cutree(Hierar_cl, k = 40)

plot(data,col=clusters,asp=1)
plot(data[which(clusters==1),],asp=1)
```

```{r}
set.seed(47)
par(mfrow=c(2,2))
for(i in 1:4){
  data <- generate.filament(200,.05,TRUE)
  plot(data)
}
```

```{r}
set.seed(47)
par(mfrow=c(2,2))
for(i in 1:4){
  data <- generate.filament(200,.08,FALSE)
  plot(data)
}
```















