---
title: "DQF_Anomaly_Demo"
output:
  pdf_document: default
  html_document: default
date: '2022-10-26'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initializing the plotting data

```{r}
set.seed(47)
x <- append(runif(10,5,10),17)
y <- rep(0,length(x))
data <- cbind(x,y)

plot.data <- function(data){
  plot.x <- seq(min(data[,1]-.5),max(data[,1]+.5),.01)
  plot(plot.x,rep(0,length(plot.x)),t='l',
     xlab="x1",
     ylab="")
  points(data,col='red')
}

plot.data(data)
data
```

```{r}
data <- apply(data, 2, scale)
data[,2] <- rep(0,length(x))
plot.data(data)
```

```{r}
draw.cone.1D <- function(conetip, point, angle, x.lim,direction){
  conetip <- as.numeric(conetip)
  slope <- tan(angle*(pi/180))
  
  if(direction == 1) x <- seq(conetip,x.lim[2],.1)
  else if(direction == -1) x <- seq(conetip,x.lim[1],-.1)
  
  y.upper <- slope*(x-conetip)
  y.lower <- -slope*(x-conetip)
  
  lines(x,y.upper,col='orange')
  lines(x,y.lower,col='orange')
  abline(v=point[1],col='orange')
}
```


```{r}
pt <- data[5,]
plot.data(data)
for(i in seq(pt[1],3,.1)){
  draw.cone.1D(i,pt,30,c(-2,4),-1)
}

plot.data(data)
for(i in seq(-2,pt[1],.1)){
  draw.cone.1D(i,pt,30,c(-2,4),1)
}
```

for(i in seq(-1,3,.1)){
  draw.cone.1D(i,data[10,],30,c(-2,4),-1)
}
```
```{r}
length(which(data[,1]>0))
```



















































