---
title: "Hierarchical Clustering + DQF"
output: html_document
date: '2022-11-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(dqfAnomaly) 
```

## Playing around with Hierarchical Clustering

```{r}
set.seed(47)

x <- c(rnorm(25,-2,.5),rnorm(25,0,.5),rnorm(25,2,.5))
y <- c(rnorm(25,0,.5),rnorm(25,2,.5),rnorm(25,0,.5))

x.anomaly <- rnorm(5,0,.1)
y.anomaly <- rnorm(5,0,.1)
data.anomaly <- cbind(x.anomaly,y.anomaly)

data <- cbind(x,y)
data <- rbind(data,data.anomaly)
labels <- c(rep(1,25),rep(2,25),rep(3,25),rep(4,5))
plot(data,col=labels)
```

```{r}
distance_mat <- dist(data, method = 'euclidean')
HC <- hclust(distance_mat, method = "average")
plot(HC)
```

```{r}
clusterCut <- cutree(HC, 5)
table(clusterCut,labels)
```

```{r}
k <- 6
par(mfrow= c(1,2))
for(i in 1:k){
  clusterCut <- cutree(HC, i)
  plot(data,col=clusterCut)
}
```

## Functional Metric for Anomaly

```{r}
set.seed(47)

x <- rnorm(100)
y <- rnorm(100)
data <- cbind(x,y)
length.data <- length(x)
x.anomaly <- seq(0,4,.33)
y.anomaly <- seq(0,4,.33)
data.anomaly <- cbind(x.anomaly,y.anomaly)
labels <- c(rep(1,length(data[,1])),rep(2,length(data.anomaly[,1])))
labels[28] <- 2
data <- rbind(data,data.anomaly)

r <- 3
circle.x <- seq(-r,r,.01)
upper.circle.y <- sqrt(r^2-circle.x^2)
lower.circle.y <- -sqrt(r^2-circle.x^2)

upper.circle <- cbind(circle.x,upper.circle.y)
lower.circle <- cbind(circle.x,lower.circle.y)
circle <- rbind(upper.circle,lower.circle)

plot(data,col=labels,asp=1)
lines(circle)
```

```{r}
dqfs <- dqf.outlier(data)
```

```{r}
length(dqfs$dqf1[,1])
length(data[,1])
```

```{r}
x <- seq(.01,1,.01)

par(mfrow = c(1,3))

plot(x,dqfs$dqf1[1,],t='l',ylim=c(0,max(dqfs$dqf1)))
for(i in 2:length(dqfs$dqf1[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf1[i,],col='red')
  } else{
    lines(x,dqfs$dqf1[i,])
  }
}

plot(x,dqfs$dqf2[1,],t='l',ylim=c(0,max(dqfs$dqf2)))
for(i in 2:length(dqfs$dqf2[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf2[i,],col='red')
  } else{
    lines(x,dqfs$dqf2[i,])
  }
}

plot(x,dqfs$dqf3[1,],t='l',ylim=c(0,max(dqfs$dqf3)))
for(i in 2:length(dqfs$dqf3[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf3[i,],col='red')
  } else{
    lines(x,dqfs$dqf3[i,])
  }
}
```

```{r}
dqf1.means <- c()
dqf1.sds <- c()
for(i in 1:length(dqfs$dqf1[1,])){
  dqf1.means <- c(dqf1.means, mean(dqfs$dqf1[,i]))
  dqf1.sds <- c(dqf1.sds, sd(dqfs$dqf1[,i]))
}
dqf1.upper <- dqf1.means+2*dqf1.sds
dqf1.lower <- dqf1.means-2*dqf1.sds

dqf2.means <- c()
dqf2.sds <- c()
for(i in 1:length(dqfs$dqf2[1,])){
  dqf2.means <- c(dqf2.means, mean(dqfs$dqf2[,i]))
  dqf2.sds <- c(dqf2.sds, sd(dqfs$dqf2[,i]))
}
dqf2.upper <- dqf2.means+2*dqf2.sds
dqf2.lower <- dqf2.means-2*dqf2.sds

dqf3.means <- c()
dqf3.sds <- c()
for(i in 1:length(dqfs$dqf3[1,])){
  dqf3.means <- c(dqf3.means, mean(dqfs$dqf3[,i]))
  dqf3.sds <- c(dqf3.sds, sd(dqfs$dqf3[,i]))
}
dqf3.upper <- dqf3.means+2*dqf3.sds
dqf3.lower <- dqf3.means-2*dqf3.sds
```

```{r}
par(mfrow = c(1,3))

#dqf1
plot(x,dqfs$dqf1[1,],t='l',ylim=c(0,max(dqfs$dqf1)))
for(i in 2:length(dqfs$dqf1[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf1[i,],col='red')
  } else{
    lines(x,dqfs$dqf1[i,])
  }
}
lines(x,dqf1.means,col='blue',t='l')
lines(x,dqf1.upper,col='blue',t='l')
lines(x,dqf1.lower,col='blue',t='l')

#dqf2
plot(x,dqfs$dqf2[1,],t='l',ylim=c(0,max(dqfs$dqf2)))
for(i in 2:length(dqfs$dqf2[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf2[i,],col='red')
  } else{
    lines(x,dqfs$dqf2[i,])
  }
}
lines(x,dqf2.means,col='blue',t='l')
lines(x,dqf2.upper,col='blue',t='l')
lines(x,dqf2.lower,col='blue',t='l')

#dqf3
plot(x,dqfs$dqf3[1,],t='l',ylim=c(0,max(dqf3.means+2*dqf3.sds)))
for(i in 2:length(dqfs$dqf3[,1])){
  if(i > length(data[,1])-6){
    lines(x,dqfs$dqf3[i,],col='red')
  } else{
    lines(x,dqfs$dqf3[i,])
  }
}
lines(x,dqf3.means,col='blue',t='l')
lines(x,dqf3.upper,col='blue',t='l')
lines(x,dqf3.lower,col='blue',t='l')
```
```{r}
length(dqf1.means)
length(dqfs$dqf1[1,])
```

```{r}
func.2norm <- function(dqf1,dqf2){
  sqrt(sum((dqf1-dqf2)^2))
}
```

```{r}
func.2norm(dqf2.means,dqf2.lower)
func.2norm(dqf2.means,dqf2.upper)
```

```{r}
par(mfrow = c(1,3))

dqf1.2norm <- c()
l1 <- c()
dqf1.bound.2norm <- func.2norm(dqf1.upper,dqf1.means)
for(i in 1:length(dqfs$dqf1[,1])){
  norm <- func.2norm(dqf1.means,dqfs$dqf1[i,])
  dqf1.2norm <- c(dqf1.2norm, norm)
  
}
plot(dqf1.2norm)
abline(h=dqf1.bound.2norm)

dqf2.2norm <- c()
for(i in 1:length(dqfs$dqf2[,1])){
  dqf2.2norm <- c(dqf2.2norm, func.2norm(dqf2.means,dqfs$dqf2[i,]))
}
dqf2.bound.2norm <- func.2norm(dqf2.upper,dqf2.means)
plot(dqf2.2norm)
abline(h=dqf2.bound.2norm)

dqf3.2norm <- c()
for(i in 1:length(dqfs$dqf3[,1])){
  dqf3.2norm <- c(dqf3.2norm, func.2norm(dqf3.means,dqfs$dqf3[i,]))
}
dqf3.bound.2norm <- func.2norm(dqf3.upper,dqf3.means)
plot(dqf3.2norm)
abline(h=dqf3.bound.2norm)
```


```{r}
total.norm <- dqf1.2norm+dqf2.2norm+dqf3.2norm
total.bound <- dqf1.bound.2norm+dqf2.bound.2norm+dqf3.bound.2norm

labels <- rep(1,length(total.norm))
labels[which(total.norm >= total.bound)] <- 2

plot(total.norm, col=labels)
abline(h=total.bound)
```
```{r}
which(total.norm >= total.bound-5)
```
```{r}

```

- sup norm
- prop living outside bounds
- z-score all functions

computation
- store q_ij
  - average over different subsets/groups

## Real Data

```{r}
data(iris)
iris <- iris 
iris
```




























