---
title: "DQF Clustering Build"
output: html_document
date: "2023-06-12"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import Functions

```{r}
source("00. datasets.R")
source("01. dqf-outlier.R")
source("02. dqf-subset.R")
source("03. extract-dqf-subset.R") 
source("04. dqf-clustering.R")
```

```{r}
trimodal <- data.n.modal()
data <- trimodal$data
plot(data)
```

```{r}
dqf.s <- readRDS("./RDS Files/04a01. 3c-dqfs-s.RDS")
```

```{r}
dqfs <- extract.dqfs(dqf.s,95:150)
plot.dqf(dqfs)
```



## dqf.clustering full user input - ask for clustering method and parameter
```{r}
dqf.clustering <- function(data = NULL,dqf.s=NULL,n.clusters=20, gram.mat = NULL, g.scale=2, angle=c(45), kernel="linear", p1=1, p2=0, n.splits=100, subsample=50, z.scale=TRUE, k.w=3, adaptive=TRUE, G="norm"){
  
  # data <- scale(data)
  
  # set n.obs - to number of observations
  if (is.null(data)) n.obs <- nrow(gram.mat)
  if (is.null(gram.mat)) n.obs <- nrow(data)
  
  subsample <- n.obs # calculate all sub-samples
  
  
  # initial clustering
  move.on <- FALSE
  print("Performing initial clustering.")
  while(!move.on){
    print("Select initial clustering method,")
    print("Input '1' for hierarchical clustering.")
    print("Input '2' for k-means clustering.")
    
    s = as.character(readline())
    
    if(s=='1'){
      cluster.method <- 'HC'
      params <- c('single','complete','average','ward.D','ward.D2','median','centroid','mcquitty')
      print("Select hierarchical clustering linkage type.")
      print("Input '1' for single linkage.")
      print("Input '2' for complete linkage.")
      print("Input '3' for average linkage.")
      print("Input '4' for ward.D linkage.")
      print("Input '5' for ward.D2 linkage.")
      print("Input '6' for median linkage.")
      print("Input '7' for centroid linkage.")
      print("Input '8' for mcquitty linkage.")
      s = readline()
      tryCatch(expr = { p <- params[as.integer(s)]},
        error = function(e) { return("Invalid parameter input.")},
        warning = function(w) {},
        finally = {}
      )
    }
    else if(s=='2'){
      cluster.method <- 'KM'
      print("Type in desired `nstart` paramter for k-means clustering.")
      p = readline()
    }
    
    print(cluster.method)
    ic <- initial.cluster(data,n.clusters,cluster.method=cluster.method,p1=p)
    
    if(is.character(ic)){
      if(ic=="error.clustermethod"){
        print("Invalid cluster method input")
      }
      else if(ic=="error.parameter"){
        print("Invalid parameter input.")
      }
    }
    else{
      clusters <- ic$clusters
      inter.dists <- ic$inter.dists
      closest.pts <- ic$closest.pts
      move.on <- TRUE
    }
  }
  
  
  
  combined.clusters <- list()
  for(i in 1:n.clusters) combined.clusters[[i]] <- c(i)
  
  # calculate dqf.subset
  if(is.null(dqf.s)){
    print("Calculating `dqf.subset`...")
    dqf.s <- dqf.subset(data = data, gram.mat = gram.mat, g.scale=g.scale, angle=angle, kernel=kernel, p1=p1, p2=p2, n.splits=n.splits, subsample=subsample, z.scale=z.scale, k.w=k.w, adaptive=adaptive, G=G)
    print("`dqf.subset` calculations complete.")
  }
  
  print("We will now begin combining clusters.")
  print("You may type exit at any time and the function will return `dqf.subset` and current clusters.")
  print("Press Enter to continue")
  s = readline()
  while(s != 'exit'){
    move.on <- FALSE
    
    if(min(inter.dists)==Inf){
      final.clusters <- compile.clusters(clusters, combined.clusters)
      return(list(dqf.s=dqf.s,final.clusters=final.clusters))
    }
    mi <- which.min(inter.dists) # mi is short for min.index
    rc <- row.col(inter.dists,mi)
    row <- rc$row; col <- rc$col
    
    # Prepare dqfs
    cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
    pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
    pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2
    
    subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
    # ed1 <- extract.depths(dqf.s,subset1)
    # depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
    # qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
    # dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
    dqfs1 <- extract.dqfs(dqf.s,subset1)
    labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2
    
    subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
    # ed2 <- extract.depths(dqf.s,subset2)
    # depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
    # qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
    # dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
    dqfs2 <- extract.dqfs(dqf.s,subset2)
    labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
    
    combine.prompt(row,col,inter.dists,combined.clusters)
    
    s <- readline()
    while(!move.on){
      if(s == "Yes"){
        print(glue("Clusters {cluster.string(combined.clusters[[row]])} and {cluster.string(combined.clusters[[col]])} were combined."))
        combined.clusters <- combine.clusters(combined.clusters,row,col)
        inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
        inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
        move.on <- TRUE
      }else if(s == "No"){
        # print("Are you sure? If yes, combinning clusters {cluster.string(combined.clusters[[row]])} and {cluster.string(combined.clusters[[col]])} will not be revisited.")
        # s <- readline()
        inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf
        inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
        move.on <- TRUE
      }else if(s == "Later"){
        print("Later")
        s <- readline()
      }else if(s == row){
        plot.dqf(dqfs1,labels1)
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
      }else if(s == col){
        plot.dqf(dqfs2,labels2)
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
      } else if(s == 'exit'){
        move.on = TRUE
      } else{
        print("Invalid input")
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
      }
    }
    
  }
  
  final.clusters <- compile.clusters(clusters, combined.clusters)
  
  print("Clustering Complete. dqf.s object and final.clusters returned")
  
  return(list(dqf.s=dqf.s,final.clusters=final.clusters))
  
}
```