---
title: "DQF Clustering Build"
output: html_document
date: "2023-06-12"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, eval=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import Functions

```{r}
source("00. datasets.R")
source("01. dqf-outlier.R")
source("02. dqf-subset.R")
source("03. extract-dqf-subset.R") 
source("04. dqf-clustering.R")
```

```{r}
trimodal <- data.n.modal()
data <- trimodal$data
plot(data)
```

```{r}
dqf.s <- readRDS("./RDS Files/04a01. 3c-dqfs-s.RDS")
```

```{r}
dqfs <- extract.dqfs(dqf.s,95:150)
plot.dqf(dqfs)
```

```{r}
dqf.clustering <- function(data = NULL,dqf.s=NULL,initial.clusters=NULL,n.clusters=NULL,cluster.method=NULL,cluster.param=NULL, gram.mat = NULL, g.scale=2, angle=c(45), kernel="linear", p1=1, p2=0, n.splits=100, subsample=50, z.scale=TRUE, k.w=3, adaptive=TRUE, G="norm"){
  
  # data <- scale(data)
  
  # set n.obs - to number of observations
  if (is.null(data)) n.obs <- nrow(gram.mat)
  if (is.null(gram.mat)) n.obs <- nrow(data)
  
  # calculate all sub-samples
  subsample <- n.obs

  # clustering
  # check if user provided initial clusters
  if(is.null(initial.clusters)){
    # perform initial clustering
    print("Starting clusters not inputted. Performing initial clustering.")
    print("---")
    
    if(is.null(cluster.method)){
      print("Starting clusters not inputted. Performing single linkage hierarchical clustering.")
      print("---")
      cluster.method <- "HC"
      cluster.param <- "single"
    }
    
    if(is.null(n.clusters)){
      print("Starting number of clusters not inputted. Defaulting to 10 initial clusters")
      print("---")
      n.clusters <- 10
    }
    
    print("Performing initial clustering.")
    
    if(is.null(cluster.method)){
      cluster.method <- "HC"
      cluster.param <- "single"
    }
    
    ic <- initial.cluster(data,n.clusters,cluster.method=cluster.method,p1=cluster.param)
    
    if(is.character(ic)){
      if(ic == "error.parameter"){
        print("Invalid input for cluster.param")
        return()
      }
      else if(ic == "error.clustermethod"){
        print("Invalid input for cluster.method")
        return()
      }
    }
    else{
      clusters <- ic$clusters
      inter.dists <- ic$inter.dists
      closest.pts <- ic$closest.pts
    }
    
  }
  else{
    print("Starting clusters inputted. Calculating inter-cluster distances.")
    print("---")
    ic <- calculate.inter.dists(data, clusters)
    clusters <- ic$clusters
    inter.dists <- ic$inter.dists
    closest.pts <- ic$closest.pts
  }
  

  # set up clusters data structure for combining clusters
  # contains lists of combined clusters, indexed by initial clusters
  combined.clusters <- list()
  for(i in 1:n.clusters) combined.clusters[[i]] <- c(i)
  
  # calculate dqf.subset
  if(is.null(dqf.s)){
    print("Calculating `dqf.subset`...")
    dqf.s <- dqf.subset(data = data, gram.mat = gram.mat, g.scale=g.scale, angle=angle, kernel=kernel, p1=p1, p2=p2, n.splits=n.splits, subsample=subsample, z.scale=z.scale, k.w=k.w, adaptive=adaptive, G=G)
    print("`dqf.subset` calculations complete.")
  }
  else{
    print("dqf.s object provided.")
    print("---")
  }
  
  print("We will now begin combining clusters.")
  print("You may type exit at any time and the function will return `dqf.subset` and current clusters.")
  print("Press Enter to continue")
  s = readline()
  while(s != 'exit'){
    move.on <- FALSE
    
    if(min(inter.dists)==Inf){
      final.clusters <- compile.clusters(clusters, combined.clusters)
      
      print("Clustering Complete. dqf.s object and final.clusters returned.")
      
      return(list(dqf.s=dqf.s,final.clusters=final.clusters))
    }
    
    max.dist <- max.dist(inter.dists)
    mi <- which.min(inter.dists) # mi is short for min.index
    rc <- row.col(inter.dists,mi)
    row <- rc$row; col <- rc$col
    
    # Prepare dqfs
    cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
    pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
    pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2
    
    subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
    dqfs1 <- extract.dqfs(dqf.s,subset1)
    labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2
    
    subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
    dqfs2 <- extract.dqfs(dqf.s,subset2)
    labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
    
    diag.num <- row
    combine.prompt(row,col,inter.dists,combined.clusters)
    
    s <- readline()
    while(!move.on){
      if(s == "Yes"){
        print(glue("Clusters {cluster.string(combined.clusters[[row]])} and {cluster.string(combined.clusters[[col]])} were combined."))
        combined.clusters <- combine.clusters(combined.clusters,row,col)
        inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
        inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
        move.on <- TRUE
      }else if(s == "No"){
        inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf
        inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
        move.on <- TRUE
      }else if(s == "pp"){
        inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- inter.dists[combined.clusters[[row]],combined.clusters[[col]]] + max.dist
        inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- inter.dists[combined.clusters[[col]],combined.clusters[[row]]] + max.dist
        move.on <- TRUE
      }else if(s %in% combined.clusters[[row]]){
        plot.dqf(dqfs1,labels1)
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
        diag.num <- s
      }else if(s %in% combined.clusters[[col]]){
        plot.dqf(dqfs2,labels2)
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
        diag.num <- s
      }else if(s == 'd'){
        if(diag.num %in% combined.clusters[[row]]){
          dqf.c.diagnostics(dqfs1,labels1)
          combine.prompt(row,col,inter.dists,combined.clusters)
          s <- readline()
        } else{
          dqf.c.diagnostics(dqfs2,labels2)
          combine.prompt(row,col,inter.dists,combined.clusters)
          s <- readline()
        }
        par(mfrow=c(1,1))
      }
      else if(s == 'exit'){
        move.on = TRUE
      }else{
        print("Invalid input")
        combine.prompt(row,col,inter.dists,combined.clusters)
        s <- readline()
      }
    }
    
  }
  
  final.clusters <- compile.clusters(clusters, combined.clusters)
  
  print("Process terminated. dqf.s object and final.clusters returned.")
  
  return(list(dqf.s=dqf.s,final.clusters=final.clusters))
  
}
```



