---
title: "Hierarchical Clustering and DQFs"
output:
  pdf_document: default
  html_document: default
date: '2022-11-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(mlbench)
require(dqfAnomaly)
```

Datasets:
- Half moon
- Circles

```{r}
set.seed(47)
x <- seq(-20,20,.5)
x1 <- x+20
y1 <- (x-2)^2 + rnorm(length(x),0,30)
y2 <- -(x+2)^2 + 500 + rnorm(length(x),0,30)

data1 <- cbind(x,y1)
data2 <- cbind(x1,y2)
m.data <- rbind(data1,data2)
m.labels <- c(rep(1,length(data1[,1])),rep(2,length(data2[,1])))

plot(x,y1,xlim=c(-20,40),ylim=c(min(y1,y2),max(y1,y2)))
points(x1,y2)

plot(m.data,col=m.labels)
```

```{r}
m.data.scaled <- scale(m.data)
plot(m.data.scaled,col=m.labels)
```

```{r}
distance_mat <- dist(m.data.scaled, method = 'euclidean')
HC <- hclust(distance_mat, method = "single")
plot(HC)

clusterCut <- cutree(HC, 3)
table(clusterCut,m.labels)

plot(m.data.scaled,col=clusterCut)
```

Circles dataset

```{r}
set.seed(4747)
x1 <- c(runif(20,-1,1),seq(-1,-.9,.03),seq(.9,1,.03))
y1.1 <- sqrt(1-x1^2) + rnorm(length(x1),0,.1)
y1.2 <- -sqrt(1-x1^2) + rnorm(length(x1),0,.1)
c.data <- rbind(cbind(x1,y1.1),cbind(x1,y1.2))

x2 <- c(runif(40,-2,2),seq(-2,-1.8,.03),seq(1.8,2,.03))
y2.1 <- sqrt(4-x2^2) + rnorm(length(x2),0,.1)
y2.2 <- -sqrt(4-x2^2) + rnorm(length(x2),0,.1)
c.data <- rbind(c.data,rbind(cbind(x2,y2.1),cbind(x2,y2.2)))

x3 <- c(runif(60,-3,3),seq(-3,-2.7,.03),seq(2.7,3,.03))
y3.1 <- sqrt(9-x3^2) + rnorm(length(x3),0,.1)
y3.2 <- -sqrt(9-x3^2) + rnorm(length(x3),0,.1)
c.data <- rbind(c.data,rbind(cbind(x3,y3.1),cbind(x3,y3.2)))

c.labels <- c(rep(1,2*length(x1)),rep(2,2*length(x2)),rep(3,2*length(x3)))

plot(c.data,asp=1,col=c.labels)
```

```{r}
distance_mat <- dist(c.data, method = 'euclidean')
HC <- hclust(distance_mat, method = "single")
plot(HC)

clusterCut <- cutree(HC, 3)
table(clusterCut,c.labels)

plot(c.data,col=clusterCut,asp=1)
```

```{r}
c.data.scaled <- scale(c.data)

distance_mat <- dist(c.data.scaled, method = 'euclidean')
HC <- hclust(distance_mat, method = "single")
plot(HC)

clusterCut <- cutree(HC, 19)
table(clusterCut,c.labels)

plot(c.data.scaled,col=clusterCut,asp=1)
```
```{r}
table(clusterCut)
```

```{r}
plot(c.data[c(which(clusterCut == 4),1),],ylim=c(-2.5,2.5),xlim=c(-3,3))
```

```{r}
dqf <- dqf.outlier(c.data[c(which(clusterCut == 4),1),])
```

```{r}
dqf.explore(dqf,71)
```

```{r}
source("5a01-DQF-USMetrics.R")
```

```{r}
labels <- c(rep(1,70),2)
plot.dqf(dqf$dqf3,labels)
```
```{r}
plot.dqf(scale.dqf.sum(dqf$dqf3),labels)
```

```{r}
plot.dqf(dqf$dqf3,labels)
draw.mean.bounds(dqf.mean(dqf$dqf3),dqf.sd(dqf$dqf3),2)
```



```{r}
plot.mean.zscores(dqf$dqf3,labels)
indices <- which(dqf.mean.zscore(dqf$dqf3) >= (dqf.mean.zscore(dqf$dqf3)[71]))
l <- rep(1,71)
for(i in indices) l[i] <- 2
plot.mean.zscores(dqf$dqf3,l)
```


```{r}
plot(c.data[c(which(clusterCut == 4),1),],ylim=c(-2.5,2.5),xlim=c(-3,3),col=l)
```


```{r}
plot.prop.outside.bounds(dqf$dqf3)
```

```{r}
indices.outside <- which(prop.outside.bounds(dqf$dqf3)>.2)
l2 <- rep(1,71)
for(i in indices.outside) l2[i] <- 2
plot(c.data[c(which(clusterCut == 4),1),],ylim=c(-2.5,2.5),xlim=c(-3,3),col=l2)
```

- edge data points
- percentile?

```{r}
indices4 <- which(clusterCut==4)
indices5 <- which(clusterCut == 5)
l4 <- rep(1,length(indices4))
l5 <- rep(2,length(indices5))
l45 <- c(l4,l5)
plot(c.data[c(indices4,indices5),],ylim=c(-2.5,2.5),xlim=c(-3,3),col=l45)
```
```{r}
plot(c.data[c(indices4,indices5[1]),],ylim=c(-2.5,2.5),xlim=c(-3,3),col=c(l4,2))
```

```{r}
plot.dqf(scale.dqf.max(dqf$dqf3),labels)
```

```{r}
dqf2 <- dqf.outlier(c.data[c(indices4,indices5[1]),])
```

```{r}
length(c.data[c(indices4,indices5[1]),])
```

```{r}
labels <- c(rep(1,70),2)
plot(c.data[c(indices4,indices5[1]),],col=labels)
plot.dqf(dqf2$dqf3,labels)

plot.dqf(dqf2$dqf3,labels)
draw.mean.bounds(dqf.mean(dqf$dqf3),dqf.sd(dqf$dqf3),2)

plot.mean.zscores(dqf2$dqf3,labels)
indices <- which(dqf.mean.zscore(dqf$dqf3) >= (dqf.mean.zscore(dqf$dqf3)[71]))
l <- rep(1,71)
for(i in indices) l[i] <- 2
plot.mean.zscores(dqf2$dqf3,l)
plot.prop.outside.bounds(dqf2$dqf3)
```

```{r}
plot.dqf(scale.dqf.max(dqf2$dqf3),labels)
```

- derivatives
- human involvement, similar to dqf.explore
- 














