---
title: "Thesis Figures"
output: html_document
date: '2022-11-12'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(47)
x <- c(runif(10,0,1),.6,.6)
y <- c(runif(10,0,1),.3,.7)
labels <- c(rep(1,10),c(3,4))
draw.circle <- function(center.x,center.y,radius,col){
  x <- center.x
  y <- center.y
  r <- radius
  
  circle.x <- seq(x-r,x+r,.01)
  upper.circle.y <- y+sqrt(r^2-(circle.x-x)^2)
  lower.circle.y <- y-sqrt(r^2-(circle.x-x)^2)
  
  upper.circle <- cbind(circle.x,upper.circle.y)
  lower.circle <- cbind(circle.x,lower.circle.y)
  circle <- rbind(upper.circle,lower.circle)
  
  lines(circle,col=col)
}
for(i in 1:10){
  if(x[i]+y[i] > 1) labels[i] <- 2
}
plot(x,y,col=labels,asp=1,ylim=c(0,1))
draw.circle(x[11],y[11],.24,3)
draw.circle(x[12],y[12],.25,4)
```

```{r}
set.seed
d1 <- cbind(rnorm(10),rnorm(20))
d2 <- cbind(rnorm(10,5),rnorm(20,5))
d3 <- cbind(rnorm(10,10),rnorm(20,10))
data <- rbind(d1,d2,d3)
data <- scale(data)
plot(data,xlab='',ylab='')
```




```{r}
set.seed(47)
x <- seq(-20,20,.5)
x1 <- x+20
y1 <- (x-2)^2 + rnorm(length(x),0,30)
y2 <- -(x+2)^2 + 500 + rnorm(length(x),0,30)
data1 <- cbind(x,y1)
data2 <- cbind(x1,y2)
m.data <- rbind(data1,data2)
m.labels <- c(rep(1,length(data1[,1])),rep(2,length(data2[,1])))
plot(x,y1,xlim=c(-20,40),ylim=c(min(y1,y2),max(y1,y2)))
points(x1,y2)
m.data <- scale(m.data)
plot(m.data,col=m.labels,xlab='',ylab='')
```

```{r}
distance_mat <- dist(m.data, method = 'euclidean')
Hierar_cl <- hclust(distance_mat, method = "average")
plot(Hierar_cl)
rect.hclust(Hierar_cl, k = 2, border = "green")
fit <- cutree(Hierar_cl, k = 2)
plot(m.data,col=fit,xlab='',ylab='',asp=1)
```



```{r}
set.seed(4747)
x1 <- c(runif(20,-1,1),seq(-1,-.9,.03),seq(.9,1,.03))
y1.1 <- sqrt(1-x1^2) + rnorm(length(x1),0,.1)
y1.2 <- -sqrt(1-x1^2) + rnorm(length(x1),0,.1)
c.data <- rbind(cbind(x1,y1.1),cbind(x1,y1.2))
x2 <- c(runif(40,-2,2),seq(-2,-1.8,.03),seq(1.8,2,.03))
y2.1 <- sqrt(4-x2^2) + rnorm(length(x2),0,.1)
y2.2 <- -sqrt(4-x2^2) + rnorm(length(x2),0,.1)
c.data <- rbind(c.data,rbind(cbind(x2,y2.1),cbind(x2,y2.2)))
x3 <- c(runif(60,-3,3),seq(-3,-2.7,.03),seq(2.7,3,.03))
y3.1 <- sqrt(9-x3^2) + rnorm(length(x3),0,.1)
y3.2 <- -sqrt(9-x3^2) + rnorm(length(x3),0,.1)
c.data <- rbind(c.data,rbind(cbind(x3,y3.1),cbind(x3,y3.2)))
c.labels <- c(rep(1,2*length(x1)),rep(2,2*length(x2)),rep(3,2*length(x3)))
c.data <- scale(c.data)
plot(c.data,asp=1,col=c.labels)
```

```{r}
par(mfrow=c(2,2))
distance_mat <- dist(c.data, method = 'euclidean')
Hierar_cl <- hclust(distance_mat, method = "average")
# plot(Hierar_cl)
# rect.hclust(Hierar_cl, k = 3, border = "green")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='average')
Hierar_cl <- hclust(distance_mat, method = "single")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='single')
Hierar_cl <- hclust(distance_mat, method = "complete")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='complete')
Hierar_cl <- hclust(distance_mat, method = "centroid")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='centroid')
```

```{r}
source("99-DQFClusteringFUnctions.R")
```

```{r}
set.seed(47)
data <- cbind(rnorm(50),rnorm(50))
data <- rbind(data,cbind(rnorm(50,5),rnorm(50,5)))
data <- rbind(data,cbind(rnorm(50,-5),rnorm(50,-5)))
data <- scale(data)
labels <- c(rep(1,50),rep(2,50),rep(3,50))
plot(data,col=labels)
```


```{r}
library(glue)
```

```{r}
dqf.s <- dqf.subset(data = data)
```

```{r}
subsample <- n.obs <- nrow(data)
n.clusters <- 6

ic <- initial.cluster(data,n.clusters)
clusters <- ic$clusters
inter.dists <- ic$inter.dists
closest.pts <- ic$closest.pts

combined.clusters <- list()
for(i in 1:n.clusters) combined.clusters[[i]] <- c(i)
```

```{r}
par(mfrow=c(1,2))
plot(data,col=labels,main='Data - Ground Truth',xlab='',ylab='')
legend(.7, -.3, legend=unique(labels),col=unique(labels), pch=1)
plot(data,col=clusters,main='Initial Clustering',xlab='',ylab='')
legend(.7, .5, legend=unique(clusters),col=unique(clusters), pch=1)
```

```{r}
mi <- which.min(inter.dists) # mi is short for min.index
rc <- row.col(inter.dists,mi)
row <- rc$row; col <- rc$col

cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2

subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
ed1 <- extract.depths(dqf.s,subset1)
depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2

subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
ed2 <- extract.depths(dqf.s,subset2)
depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
```

```{r}
par(mfrow=c(1,2))
plot.dqf(dqfs1,labels1,main=glue("C{row} and Pt in C{col}"))
plot.dqf(dqfs2,labels2,main=glue("C{col} and Pt in C{row}"))
```

```{r}
combined.clusters <- combine.clusters(combined.clusters,row,col)
inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
c1 <- compile.clusters(clusters, combined.clusters)
```

```{r}
plot(data,col=c1)
legend(1.3, .5, legend=unique(c1),col=unique(c1), pch=1)
```

```{r}
mi <- which.min(inter.dists) # mi is short for min.index
rc <- row.col(inter.dists,mi)
row <- rc$row; col <- rc$col

cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2

subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
ed1 <- extract.depths(dqf.s,subset1)
depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2

subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
ed2 <- extract.depths(dqf.s,subset2)
depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
```

```{r}
combine.prompt(row,col,inter.dists,combined.clusters)

par(mfrow=c(1,2))
plot.dqf(dqfs1,labels1,main=glue("C{row} and pt in C{col}"))
plot.dqf(dqfs2,labels2,main=glue("C{col} and pt in C{row}"))
```

```{r}
combined.clusters <- combine.clusters(combined.clusters,row,col)
inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
c2 <- compile.clusters(clusters, combined.clusters)
```

```{r}
plot(data,col=c2)
legend(1.3, .5, legend=unique(c2),col=unique(c2), pch=1)
```

```{r}
mi <- which.min(inter.dists) # mi is short for min.index
rc <- row.col(inter.dists,mi)
row <- rc$row; col <- rc$col

cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2

subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
ed1 <- extract.depths(dqf.s,subset1)
depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2
```

```{r}
subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
ed2 <- extract.depths(dqf.s,subset2)
depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
```

```{r}
combine.prompt(row,col,inter.dists,combined.clusters)

par(mfrow=c(1,2))
plot.dqf(dqfs1,labels1,main=glue("C{row} and pt in C{col}"))
plot.dqf(dqfs2,labels2,main=glue("C{col} and pt in C{row}"))
```

```{r}
combined.clusters <- combine.clusters(combined.clusters,row,col)
inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
c3 <- compile.clusters(clusters, combined.clusters)
```

```{r}
plot(data,col=c3)
legend(1.3, .5, legend=unique(c3),col=unique(c3), pch=1)
```

```{r}
mi <- which.min(inter.dists) # mi is short for min.index
rc <- row.col(inter.dists,mi)
row <- rc$row; col <- rc$col
row <- 5; col <- 1

cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2

subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
ed1 <- extract.depths(dqf.s,subset1)
depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2

subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
ed2 <- extract.depths(dqf.s,subset2)
depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
```

```{r}
d1 <- dqfs1
```

```{r}
combine.prompt(row,col,inter.dists,combined.clusters)

par(mfrow=c(1,2))
plot.dqf(dqfs1,labels1,main=glue("C{row} and pt in C{col}"))
plot.dqf(dqfs2,labels2,main=glue("C{row} and pt in C2"))
```

```{r}
inter.dists[combined.clusters[[row]],combined.clusters[[col]]] <- Inf # don't need to consider combining them anymore
inter.dists[combined.clusters[[col]],combined.clusters[[row]]] <- Inf
```

```{r}
mi <- which.min(inter.dists) # mi is short for min.index
rc <- row.col(inter.dists,mi)
row <- rc$row; col <- rc$col

cpc <- closest.pt.clusters(inter.dists,combined.clusters[[row]],combined.clusters[[col]])
pt2.index <- closest.pts[cpc$c1,cpc$c2] # index of closest point in cluster group 2 to cg1
pt1.index <- closest.pts[cpc$c2,cpc$c1] # index of closest point in cluster group 1 to cg2

subset1 <- c(all.indices(clusters,combined.clusters[[row]]),pt2.index)
ed1 <- extract.depths(dqf.s,subset1)
depths1 <- ed1$depths; subset1.pairs <- ed1$subset.pairs
qfs1 <- calculate.qfs(depths=depths1,dqf.s$k.to.mids,dqf.s$splits)
dqfs1 <- calculate.dqfs(qfs1,subset1.pairs,subset1,n.obs)
labels1 <- rep(1,length(subset1)); labels1[which(subset1==pt2.index)] <- 2

subset2 <- c(all.indices(clusters,combined.clusters[[col]]),pt1.index)
ed2 <- extract.depths(dqf.s,subset2)
depths2 <- ed2$depths; subset2.pairs <- ed2$subset.pairs
qfs2 <- calculate.qfs(depths=depths2,dqf.s$k.to.mids,dqf.s$splits)
dqfs2 <- calculate.dqfs(qfs2,subset2.pairs,subset2,n.obs)
labels2 <- rep(1,length(subset2)); labels2[which(subset2==pt1.index)] <- 2
```

```{r}
plot.dqf(dqfs1,labels1,main=glue("C{row} and pt in C{col}"))
plot.dqf(dqfs2,labels2,main=glue("C1 and pt in C2"))
```

```{r}
par(mfrow=c(2,2))
plot(data,col=clusters,main='1',xlab='',ylab='')
plot(data,col=c1,main='2',xlab='',ylab='')
plot(data,col=c2,main='3',xlab='',ylab='')
plot(data,col=c3,main='4',xlab='',ylab='')
```

## iris data

```{r}
source("99-DQFClusteringFUnctions.R")
```

```{r}
data(iris)
library(dplyr)
gt.clus <- c()
for(s in iris$Species){
  if(s=="setosa") gt.clus <- c(gt.clus,1)
  else if(s=="versicolor") gt.clus <- c(gt.clus,2)
  else if(s=="virginica") gt.clus <- c(gt.clus,3)
}
i.data <- cbind(iris,gt.clus)
i.data <- i.data[,1:4]
head(i.data)
```










