---
title: "Thesis Figures"
output: html_document
date: '2022-11-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(47)
x <- c(runif(10,0,1),.6,.6)
y <- c(runif(10,0,1),.3,.7)
labels <- c(rep(1,10),c(3,4))

draw.circle <- function(center.x,center.y,radius,col){
  x <- center.x
  y <- center.y
  r <- radius
  
  circle.x <- seq(x-r,x+r,.01)
  upper.circle.y <- y+sqrt(r^2-(circle.x-x)^2)
  lower.circle.y <- y-sqrt(r^2-(circle.x-x)^2)
  
  upper.circle <- cbind(circle.x,upper.circle.y)
  lower.circle <- cbind(circle.x,lower.circle.y)
  circle <- rbind(upper.circle,lower.circle)
  
  lines(circle,col=col)
}

for(i in 1:10){
  if(x[i]+y[i] > 1) labels[i] <- 2
}

plot(x,y,col=labels,asp=1,ylim=c(0,1))
draw.circle(x[11],y[11],.24,3)
draw.circle(x[12],y[12],.25,4)
```

```{r}
set.seed
d1 <- cbind(rnorm(10),rnorm(20))
d2 <- cbind(rnorm(10,5),rnorm(20,5))
d3 <- cbind(rnorm(10,10),rnorm(20,10))
data <- rbind(d1,d2,d3)
data <- scale(data)
plot(data,xlab='',ylab='')
```




```{r}
set.seed(47)
x <- seq(-20,20,.5)
x1 <- x+20
y1 <- (x-2)^2 + rnorm(length(x),0,30)
y2 <- -(x+2)^2 + 500 + rnorm(length(x),0,30)
data1 <- cbind(x,y1)
data2 <- cbind(x1,y2)
m.data <- rbind(data1,data2)
m.labels <- c(rep(1,length(data1[,1])),rep(2,length(data2[,1])))
plot(x,y1,xlim=c(-20,40),ylim=c(min(y1,y2),max(y1,y2)))
points(x1,y2)
m.data <- scale(m.data)
plot(m.data,col=m.labels,xlab='',ylab='')
```

```{r}
distance_mat <- dist(m.data, method = 'euclidean')
Hierar_cl <- hclust(distance_mat, method = "average")
plot(Hierar_cl)
rect.hclust(Hierar_cl, k = 2, border = "green")
fit <- cutree(Hierar_cl, k = 2)
plot(m.data,col=fit,xlab='',ylab='',asp=1)
```



```{r}
set.seed(4747)
x1 <- c(runif(20,-1,1),seq(-1,-.9,.03),seq(.9,1,.03))
y1.1 <- sqrt(1-x1^2) + rnorm(length(x1),0,.1)
y1.2 <- -sqrt(1-x1^2) + rnorm(length(x1),0,.1)
c.data <- rbind(cbind(x1,y1.1),cbind(x1,y1.2))
x2 <- c(runif(40,-2,2),seq(-2,-1.8,.03),seq(1.8,2,.03))
y2.1 <- sqrt(4-x2^2) + rnorm(length(x2),0,.1)
y2.2 <- -sqrt(4-x2^2) + rnorm(length(x2),0,.1)
c.data <- rbind(c.data,rbind(cbind(x2,y2.1),cbind(x2,y2.2)))
x3 <- c(runif(60,-3,3),seq(-3,-2.7,.03),seq(2.7,3,.03))
y3.1 <- sqrt(9-x3^2) + rnorm(length(x3),0,.1)
y3.2 <- -sqrt(9-x3^2) + rnorm(length(x3),0,.1)
c.data <- rbind(c.data,rbind(cbind(x3,y3.1),cbind(x3,y3.2)))
c.labels <- c(rep(1,2*length(x1)),rep(2,2*length(x2)),rep(3,2*length(x3)))
c.data <- scale(c.data)
plot(c.data,asp=1,col=c.labels)
```

```{r}
par(mfrow=c(2,2))
distance_mat <- dist(c.data, method = 'euclidean')
Hierar_cl <- hclust(distance_mat, method = "average")
# plot(Hierar_cl)
# rect.hclust(Hierar_cl, k = 3, border = "green")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='average')

Hierar_cl <- hclust(distance_mat, method = "single")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='single')

Hierar_cl <- hclust(distance_mat, method = "complete")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='complete')

Hierar_cl <- hclust(distance_mat, method = "centroid")
fit <- cutree(Hierar_cl, k = 3)
plot(c.data,col=fit,xlab='',ylab='',asp=1,main='centroid')
```













